### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by ryo33** [Yayaka/Amorphos#10]
I plan to extract Yayaka subprotocol from Yayaka Protocol and rename Yayaka Protocol.

Here are choices I think:
- Highly Distributed Services Messaging Protocol
- Yayaka Messaging Protocol

Here are other choices:
- Yayaka Meta Protocol (from @kuy)

**Comment by ghost** [comment]
https://github.com/Yayaka/Yayaka/issues/1
